const classifiedKeywords = {
    "variables": {
        "var": "משתנה",
        "let": "יהי",
        "const": "קבוע",
    },
    "function": {
        "function": "יכולת",
        "return": "החזירי",
        "yield": "הנבי",
        "arguments": "טיעונים",
    },
    "boolean": {
        "true": "אמת",
        "false": "שקר",
    },
    "if": {
        "if": "אם",
        "else": "אחרת",
    },
    "loops": {
        "for": "עבור",
        "of": "של",
        "in": "מתוך",
        "while": "כאשר",
        "do": "עשי",
        "break": "שברי",
        "continue": "המשיכי",
    },
    "switch": {
        "switch": "החליפי",
        "case": "מקרה",
        "default": "ברירתמחדל",
    },
    "try": {
        "try": "נסי",
        "catch": "תפסי",
        "finally": "ולבסוף",
        "throw": "זרקי",
    },
    "oop": {
        "class": "מחלקה",
        "this": "אנוכי",
        "new": "צרי",
        "null": "כלום",
        "extends": "מרחיבה",
        "super": "אמא",
        "instanceof": "מסוג",
        "static": "נייח",
    },
    "other": {
        "delete": "השמידי",
        "typeof": "סוגשל",
        "goto": "לכיאל",
        "eval": "שערכי",
        "with": "עם",
        "debugger": "קוטלחרקים",
        "import": "ייבאי",
        "export": "ייצאי",
    },
    "safety": {
        "package": "חבילה",
        "interface": "ממשק",
        "implements": "מיישמת",
        "private": "פרטי",
        "protected": "מוגן",
        "public": "פומבי",
        "native": "יליד",
        "synchronized": "מתואם",
        "throws": "זורק",
        "transient": "חולף",
        "void": "ריק",
        "volatile": "תנודתי",
        "enum": "מנייה",
        "final": "סופי",
    },
    "types": {
        "float": "צף",
        "int": "שלם",
        "long": "ארוך",
        "char": "תו",
        "short": "קצר",
        "double": "דובל",
        "byte": "בית",
        "boolean": "בוליאן",
    },
};
const classifiedDictionary = {
    "generic": {
        "console": "בקרה",
        "undefined": "תוהו",
        "NaN": "לאמספר",
        "Infinity": "אינסוף",
        "JSON": "פנחס",
        "prototype": "אבטיפוס",
        "constructor": "בנאי",
        "eval": "שערכי",
        "window": "חלון"
    },
    "functions": {
        "setTimeout": "קבעי_תזמון",
        "clearTimeout": "בטלי_תזמון",
        "setInterval": "קבעי_חזרתיות",
        "clearInterval": "בטלי_חזרתיות",
        "parseFloat": "נתחי_צף",
        "parseInt": "נתחי_שלם",
        "isFinite": "האם_סופי",
        "isNaN": "האם_לאמספר",
        "decodeURI": "פענחי_כתובת_אתר",
        "decodeURIComponent": "פענחי_רכיב_כתובת_אתר",
        "encodeURI": "קודדי_כתובת_אתר",
        "encodeURIComponent": "קודדי_רכיב_כתובת_אתר",
        "escape": "בצעי_בריחה",
        "unescape": "בטלי_בריחה",
        "require": "דרשי",
        "Image":"צרי_תמונה"
    },
    "classes": {
        "Object": "עצם",
        "Function": "היכולת",
        "Boolean": "הבוליאן",
        "Number": "מספר",
        "Date": "תאריך",
        "String": "המחרוזת",
        "RegExp": "ביטוי_סדיר",
        "Array": "מערך",
        "Buffer": "חיץ",
        "Set": "קבוצה",
        "Map": "מפה",
        "Promise": "הבטחה",
        "Math": "חשבון"
    },
    "console": {
        "error": "שגיאה",
        "log": "תעד",
        "clear": "נקה",
        "debug": "ניפוי",
        "info": "מידע",
        "trace": "עקבות",
        "warn": "הזהר",
    },
    "DomElements":{
        "document": "מסמך",
        "window": "חלון",
        "body": "גוף",
        "head": "ראש",
    },
    "DomElementMethods":{
        "createElement":"צור_איבר",
        "querySelector": "בחר_על_ידי_שאילתא",
        "querySelector": "בחר_על_ידי_שאילתא_את_כולם",
        "appendChild":"הוסף_ילד",
        "removeChild":"הסר_ילד",
        "replaceChild":"החלף_ילד",
        "insertBefore":"הכנס_לפני",
        "getElementById":"קבל_איבר_על_פי_מזהה",
        "getElementsByTagName":"קבל_איברים_על_פי_שם_תג",
        "getElementsByClassName":"קבל_איברים_על_פי_שם_מחלקה",
        "addEventListener":"הוסף_מאזין_ארוע",
        "removeEventListener":"הסר_מאזין_ארוע",
        "setAttribute":"קבע_תכונה",
        "getAttribute":"קבל_תכונה",
        "removeAttribute":"הסר_תכונה",
        "hasAttribute":"כולל_תכונה",
        "hasChildNodes":"כולל_ילדים",
        "cloneNode":"שכפל_צומת",
        "normalize":"נורמלי",
        "isEqualNode":"האם_שווה_צומת",
        "isSameNode":"האם_אותו_צומת",
        "compareDocumentPosition":"השווה_מיקום_מסמך",
        "contains":"מכיל",
        "lookupPrefix":"חפש_קידומת",
        "lookupNamespaceURI":"חפש_כתובת_מרחב_שם",
        "isDefaultNamespace":"האם_מרחב_שם_ברירת_מחדל",
        "nodeType":"סוג_צומת",
        "nodeName":"שם_צומת",
        "baseURI":"כתובת_בסיס",
        "textContent":"תוכן_טקסט",
        "innerHTML":"הטמל_פנימי",
        "classList":"רשימת_מחלקה",
        "style":"סגנון",
        "getBoundingClientRect":"קבל_מעגל_מסוגל",
        "clientHeight":"גובה_מטרה",
        "clientWidth":"רוחב_מטרה",
        "offsetHeight":"גובה_פער",
        "offsetWidth":"רוחב_פער",
        "offsetTop":"פער_עליון",
        "offsetLeft":"פער_שמאלי",
        "previousElementSibling":"האחה_הבא",
        "nextElementSibling":"האח_הקודם",
        "parentElement":"איבר_אבא",
        "children":"ילדים",
        "matches":"מתאימים",
    },
    "json": {
        "stringify": "מחרז",
        "parse": "פענח"
    },
    "promise": {
        "reject": "הפר",
        "resolve": "ממש",
        "all": "כולם",
        "race": "מירוץ",
        "then": "ואז",
        "catch": "תפוס",
    },
    "math": {
        "abs": "ערך_מוחלט",
        "ceil": "תקרה",
        "floor": "רצפה",
        "max": "מירבי",
        "min": "מזערי",
        "pow": "חזקה",
        "random": "אקראי",
        "round": "עגל",
        "sqrt": "שורש",
    },
    "htmlAttributes": {
        "class": "קבוצה",
        "dir": "כיוון",
        "hidden": "מוסתר",
        "id": "מזהה",
        "style": "עיצוב",
        "title": "כותרת",
        "src": "מקור",
        "href": "כתובת_אתר",
    },
    "array": {
        "concat": "שרשר",
        "length": "אורך",
        "entries": "רשומות",
        "filter": "סנן",
        "find": "מצא",
        "forEach": "לכל",
        "includes": "כולל",
        "indexOf": "מספר_סידורי_של",
        "join": "צרף",
        "keys": "מפתחות",
        "lastIndexOf": "מספר_סידורי_אחרון_של",
        "map": "מפה",
        "pop": "שלוף",
        "push": "דחוף",
        "reduce": "צמצם",
        "reverse": "הפוך",
        "shift": "הסט",
        "slice": "פרוס",
        "some": "כלשהו",
        "sort": "מיין",
        "splice": "אחה",
        "toString": "למחרוזת",
        "unshift": "בטל_הסט",
    },
    "string": {
        "charAt": "תו_ב",
        "charCodeAt": "קוד_תו_ב",
        "endsWith": "מסתיים_ב",
        "match": "התאם",
        "repeat": "חזור",
        "replace": "החלף",
        "search": "חפש",
        "split": "פצל",
        "startsWith": "מתחיל_ב",
        "substr": "תת_מחרוז",
        "substring": "תת_מחרוזת",
        "trim": "קצץ",
    },
    "strings":{
        "'a'": "תגית_קישור",
        "'address'": "תגית_כתובת",
        "'area'": "תגית_איזור",
        "'article'": "תגית_כתבה",
        "'aside'": "תגית_הציגה",
        "'audio'": "תגית_שמע",
        "'b'": "תגית_דגש",
        "'base'": "תגית_בסיס",
        "'blockquote'": "תגית_ציטוט",
        "'body'": "תגית_גוף",
        "'br'": "תגית_שבור_שורה",
        "'button'": "תגית_כפתור",
        "'canvas'": "תגית_קנווס",
        "'code'": "תגית_קוד",
        "'col'": "תגית_עמודה",
        "'colgroup'": "תגית_קבוצת_עמודות",
        "'data'": "תגית_מידה",
        "'datalist'": "תגית_רשימת_מידע",
        "'details'": "תגית_פרטים",
        "'dialog'": "תגית_דיאלוג",
        "'div'": "תגית_מפריד",
        "'embed'": "תגית_הטמעה",
        "'fieldset'": "תגית_סט_שדות",
        "'footer'": "תגית_תחתית",
        "'form'": "תגית_טופס",
        "'h1'": "תגית_כ1",
        "'h2'": "תגית_כ2",
        "'h3'": "תגית_כ3",
        "'h4'": "תגית_כ4",
        "'h5'": "תגית_כ5",
        "'h6'": "תגית_כ6",
        "'head'": "תגית_ראש",
        "'header'": "תגית_כותרת",
        "'hgroup'": "תגית_קבוצת_כותרת",
        "'hr'": "תגית_קו",
        "'div'": "תגית_מפריד",
        "'span'": "תגית_מרחב",
        "'img'": "תגית_תמונה",
        //all main events 
        "'click'": "אירוע_לחיצה",
        "'dblclick'": "אירוע_לחיצה_כפולה",
        "'mousedown'": "אירוע_עכבר_למטה",
        "'mouseup'": "אירוע_עכבר_למעלה",
        "'mouseover'": "אירוע_עכבר_על_פני",
        "'mousemove'": "אירוע_עכבר_זז",
        "'mouseout'": "אירוע_עכבר_יוצא",
        "'mouseenter'": "אירוע_עכבר_נכנס",
        "'mouseleave'": "אירוע_עכבר_עוזב",
        "'mousewheel'": "אירוע_גלגלת",
        "'contextmenu'": "אירוע_תפריט_הקשר",
        "'keydown'": "אירוע_מקש_למטה",
        "'keyup'": "אירוע_מקש_למעלה",
        "'keypress'": "אירוע_מקש_נלחץ",
        "'focus'": "אירוע_מיקד",
        "'blur'": "אירוע_עזיבת_מיקוד",
        "'change'": "אירוע_שינוי",
        "'select'": "אירוע_בחירה",
        "'submit'": "אירוע_שליחה",
    }
};

function flattenObject(obj) {
    const result = {};
    for (const k in obj) {
        const nested = obj[k];
        for (const key in nested) {
            const value = nested[key];
            result[key] = value;
        }
    }
    return result;
}

export default {
    keywords: flattenObject(classifiedKeywords),
    dictionary: flattenObject(classifiedDictionary),
    chars: {
        "א": "a",
        "ב": "b",
        "ג": "g",
        "ד": "d",
        "ה": "h",
        "ו": "v",
        "ז": "z",
        "ח": "h",
        "ט": "t",
        "י": "i",
        "כ": "k",
        "ל": "l",
        "מ": "m",
        "נ": "n",
        "ס": "s",
        "ע": "a",
        "פ": "p",
        "צ": "z",
        "ק": "k",
        "ר": "r",
        "ש": "sh",
        "ת": "t",
        "ן": "n",
        "ם": "m",
        "ך": "ch",
        "ף": "f",
        "ץ": "z"
    },
    quotes: [
        '"',
        "'",
        "״",
        "׳",
    ],
    classifiedKeywords,
    classifiedDictionary,
}
